version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: weather_postgres
    environment:
      POSTGRES_USER: weatheruser
      POSTGRES_PASSWORD: weatherpass
      POSTGRES_DB: weatherdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  weather_job:
    build: ./weather_job
    container_name: weather_job_container
    volumes:
      - ./data:/data
    depends_on:
      - db
    env_file:
      - ./weather_job/.env
      
  
  server:
    build:
      context: ./server
      dockerfile: docker/local.Dockerfile
    container_name: server_container
    restart: always
    command: nodemon
    volumes:
      - ./server:/usr/app
      - /usr/app/node_modules
    ports:
      - 8000:8000
    env_file:
      - ./server/.env
    depends_on:
      - db

  client:
    build:
      context: ./client
      dockerfile: docker/local.Dockerfile
    container_name: client_container
    restart: always
    command: npm run start
    volumes:
      - ./client:/usr/app
      - /usr/app/node_modules
    ports:
      - 3000:3000
    env_file:
      - ./client/.env

volumes:
  postgres_data:
